# -*- coding: utf-8 -*-
#
# CIVE70079 Computational Analysis course documentation build configuration file.
# Adapted from a sphinx-quickstart template. This file configures Sphinx to build
# the course materials (lectures, tutorials, and reference material) for the
# CIVE70079 Computational Analysis module.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

from pygments.lexers import PythonLexer
from sphinx.highlighting import lexers

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('_ext'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',  # MyST parser for Markdown support
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinxcontrib.youtube',  # Note: Install with: pip install sphinxcontrib-youtube
    'sphinx.ext.viewcode',
    'sphinx_design',  # Note: Install with: pip install sphinx-design
    'sphinxcontrib.proof',  # Note: Install with: pip install sphinxcontrib-proof
    'sphinxcontrib.bibtex',  # Note: Install with: pip install sphinxcontrib-bibtex
    'sphinx_subfigure',  # Note: Install with: pip install sphinx-subfigure
    'sphinx_math_dollar',  # Alternative to fluiddoc.mathmacro for math macros
]

# Both the class’ and the __init__ method’s docstring are concatenated and
# inserted into the class definition
autoclass_content = 'both'

# Avoid duplicate section labels across documents.
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames - support both RST and Markdown
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'From Stability to Chaos'
author = u'Harmen J. Jonker and Maarten van Reeuwijk'
copyright = u'2025, Harmen J. Jonker and Maarten van Reeuwijk'

mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

# Define custom TeX macros for HTML math rendering.
mathjax3_config = {
    "tex": {
        "macros": {
            "d": r"\mathrm{d}",
        }
    }
}

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents. Shown on the LaTeX title page: use the build date rather than
# an academic-year label, so the front page always carries today's date.
import datetime as _datetime
_today = _datetime.date.today()
release = f'{_today:%B} {_today.day}, {_today.year}'   # e.g. "July 4, 2026"
version = release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_index.md",
    "_index_all.md",
    "_includes/**",
    "*_exercises.md",
    "attic/**",
    "authoring_and_testing.md",
    "integration_strategy.md",
    "primer.md",
    "tutorial_1.md",
    # "zbibliography.md",
    "PDE_*.md",
    "src*.md",
]

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

proof_theorem_types = {
    "algorithm": "Algorithm",
    "conjecture": "Conjecture",
    "corollary": "Corollary",
    "definition": "Definition",
    "example": "Example",
    "lemma": "Lemma",
    "observation": "Observation",
    "proof": "Proof",
    "property": "Property",
    "theorem": "Theorem",
    "exercise": "Exercise",
    "tutorial": "Tutorial"
}

proof_latex_parent = "chapter"

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'finite_element'
html_theme = 'sphinx_book_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "repository_url": "https://github.com/mvreeuwijk/chaosbook",
    "use_repository_button": True,
    "use_edit_page_button": False,
    "use_issues_button": False,
    "use_download_button": False,
    "home_page_in_toc": False,
    "collapse_navigation": True,
    "navigation_depth": 1,
    "show_nav_level": 1,
    # Top header: book title (left), curated part menu (centre), GitHub (right).
    # The centre menu is a custom template (maple/_templates/navbar-center.html).
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-center.html"],
    "navbar_end": ["navbar-icon-links"],
    "icon_links": [
        {
            "name": "Download PDF",
            "url": "https://mvreeuwijk.github.io/chaosbook/chaosbook.pdf",
            "icon": "fa-solid fa-file-pdf",
            "type": "fontawesome",
        },
        {
            "name": "GitHub",
            "url": "https://github.com/mvreeuwijk/chaosbook",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        },
    ],
}

# Add any paths that contain custom themes here, relative to this directory.

# The name for this set of Sphinx documents. Set explicitly so page/tab titles
# read "<page> — From Stability to Chaos" instead of the Sphinx default
# "<project> v<release> documentation".
html_title = u'From Stability to Chaos'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# '../shared/_static' holds resources common to every language edition (CSS,
# and any shared/hand-drawn assets); '_static' holds this edition's own figures.
# Later entries win on name clashes.
html_static_path = ['../shared/_static', '_static']
html_css_files = ['custom.css']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = False

# Disable smartquotes for all builders (prevents (c) -> © in LaTeX/PDF).
smartquotes = False

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    "index": [],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'numericalmethodscoursedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_additional_files = ['../shared/custom.sty']

latex_elements = {
    'papersize': 'a4paper',
    'fontpkg': '',
    'fncychap': '',
    # Show the subtitle on the title page only (temporarily append it to \title
    # for \maketitle, then restore the plain title so it does not leak into the
    # running page header).
    'maketitle': (
        r'\makeatletter'
        r'\let\sfc@title\@title'
        r'\gdef\@title{\sfc@title\\[4mm]{\Large A Hands-On Introduction to Nonlinear Dynamics}}'
        r'\maketitle'
        r'\gdef\@title{\sfc@title}'
        r'\makeatother'
    ),
    'pointsize': '11pt',
    'releasename': "",
    'babel': '',
    'printindex': '',
    'fontenc': '',
    'inputenc': '',
    'classoptions': '',
    'utf8extra': '',
    'preamble': r'\usepackage{custom}\renewcommand{\contentsname}{Table of contents}\hypersetup{hypertexnames=false}'
               r'\usepackage{etoolbox}'
               r'\preto\appendix{\cleardoublepage\phantomsection\addcontentsline{toc}{part}{Appendices}'
               r'\renewcommand{\thefigure}{\thechapter.\arabic{figure}}'
               r'\renewcommand{\theequation}{\thechapter.\arabic{equation}}'
               r'\renewcommand{\thetable}{\thechapter.\arabic{table}}}'
               r'\pdfstringdefDisableCommands{'
               r'\def\gg{}'
               r'\def\rightarrow{}'
               r'\def\infty{}'
               r'\def\tau{}'
               r'\def\mu{}'
               r'\def\alpha{}'
               r'\def\beta{}'
               r'\def\gamma{}'
               r'\def\delta{}'
               r'\def\varepsilon{}'
               r'\def\epsilon{}'
               r'\def\omega{}'
               r'\def\Omega{}'
               r'\def\theta{}'
               r'\def\pi{}'
               r'\def\lambda{}'
               r'\def\phi{}'
               r'\def\varphi{}'
               r'\def\psi{}'
               r'\def\chi{}'
               r'\def\rho{}'
               r'\def\eta{}'
               r'\def\sigma{}'
               r'\def\zeta{}'
               r'\def\kappa{}'
               r'\def\cdot{}'
               r'\def\cdots{}'
               r'\def\ldots{}'
               r'\def\pm{}'
               r'\def\times{}'
               r'\def\le{}'
               r'\def\ge{}'
               r'\def\neq{}'
               r'\def\approx{}'
               r'\def\sim{}'
               r'\def\propto{}'
               r'\def\equiv{}'
               r'\def\quad{}'
               r'\def\qquad{}'
               r'}',
    'figure_align': 'tbp',
}

latex_documents = [
  ('index', 'main.tex', u'From Stability to Chaos',
   u'Harmen J. Jonker and Maarten van Reeuwijk', 'manual'),
  # The cookbook is a separate deliverable: its own standalone PDF.
  ('app_cookbook', 'cookbook.tex', u'The Maple Cookbook',
   u'Harmen J. Jonker and Maarten van Reeuwijk', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False
latex_toplevel_sectioning = "chapter"

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals (rendered as Appendix A, B, ...).
# The "Unresolved References" report (appendix_missing_labels) is generated by
# the converter only when references are actually missing. Include it as a LaTeX
# appendix only when that document exists, so a clean build shows no such appendix.
# Appendices belong inside the book (the cookbook is a separate document, and
# the appendices landing page is HTML-only, so neither is listed here).
latex_appendices = ['app_twobody', 'app_lorenz', 'app_polar']
if os.path.exists(os.path.join(os.path.dirname(__file__), 'appendix_missing_labels.md')):
    latex_appendices.append('appendix_missing_labels')

# If false, no module index is generated.
#latex_domain_indices = True
latex_docclass = {"manual": "book"}

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'chaoticprocesses', u'Chaotic Processes',
     [u'Harmen J. Jonker and Maarten van Reeuwijk'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'chaoticprocesses', u'Chaotic Processes',
   u'Harmen J. Jonker and Maarten van Reeuwijk', 'ChaoticProcesses', 'Chaotic Processes',
   'Miscellaneous'),
]
# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

numfig = True

numfig_format={'figure': 'Figure %s', 'table': 'Table %s', 'section': '%s'}

bibtex_bibfiles = ['../shared/refs.bib']
bibtex_encoding = "iso-8859-1"
bibtex_default_style = "apa"
bibtex_reference_style = "author_year"

# MyST parser configuration for Markdown support
myst_enable_extensions = [
    "amsmath",      # Support for LaTeX-style math
    "colon_fence",  # Support for ::: code blocks
    "deflist",      # Support for definition lists
    "dollarmath",   # Support for $...$ and $$...$$ math
    "html_admonition",  # Support for admonitions
    "html_image",   # Support for HTML image tags
    "linkify",      # Automatically turn URLs into links
    "substitution", # Variable substitutions
    "tasklist",     # Support for GitHub-style task lists
]

myst_dmath_double_inline = True  # Allow $$ in inline math

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('http://docs.python.org/3/', None),
                       'scipy': ('http://docs.scipy.org/doc/scipy-dev/reference/', None),
                       'numpy': ('http://docs.scipy.org/doc/numpy/', None),
                       'matplotlib': ('http://matplotlib.org/', None)}

lexers["maple"] = PythonLexer()
